-- Die folgenden Befehle wurden nach Import der Exceltabelle nach SQL vorgenommen
ALTER TABLE `zusammenfassung` CHANGE `Nachweis` `Nachweis` VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;
UPDATE `zusammenfassung` SET `Nachweis`="K10plus" WHERE `Nachweis`="K10+"
UPDATE `zusammenfassung` SET `Sprache2`="dut" WHERE `Sprache2`="bel" 
UPDATE `Zusammenfassung` SET `IMAGE`="275" WHERE `IMAGE` = "1";
UPDATE `Zusammenfassung` SET `IMAGE`="276" WHERE `IMAGE` = "2";
UPDATE `Zusammenfassung` SET `IMAGE`="277" WHERE `IMAGE` = "3";
UPDATE `Zusammenfassung` SET `IMAGE`="278" WHERE `IMAGE` = "4";
UPDATE `Zusammenfassung` SET `IMAGE`="279" WHERE `IMAGE` = "5";
UPDATE `Zusammenfassung` SET `IMAGE`="280" WHERE `IMAGE` = "6";
UPDATE `Zusammenfassung` SET `IMAGE`="281" WHERE `IMAGE` = "7";
UPDATE `Zusammenfassung` SET `IMAGE`="282" WHERE `IMAGE` = "8";
UPDATE `Zusammenfassung` SET `IMAGE`="283" WHERE `IMAGE` = "9";
UPDATE `Zusammenfassung` SET `IMAGE`="284" WHERE `IMAGE` = "10";
UPDATE `Zusammenfassung` SET `IMAGE`="285" WHERE `IMAGE` = "11";
UPDATE `Zusammenfassung` SET `IMAGE`="286" WHERE `IMAGE` = "12";
UPDATE `Zusammenfassung` SET `IMAGE`="287" WHERE `IMAGE` = "13";
UPDATE `Zusammenfassung` SET `IMAGE`="288" WHERE `IMAGE` = "14";
UPDATE `Zusammenfassung` SET `IMAGE`="289" WHERE `IMAGE` = "15";
UPDATE `Zusammenfassung` SET `IMAGE`="290" WHERE `IMAGE` = "16";
UPDATE `Zusammenfassung` SET `IMAGE`="291" WHERE `IMAGE` = "17";
UPDATE `Zusammenfassung` SET `IMAGE`="292" WHERE `IMAGE` = "18";
UPDATE `Zusammenfassung` SET `IMAGE`="293" WHERE `IMAGE` = "19";
UPDATE `Zusammenfassung` SET `IMAGE`="294" WHERE `IMAGE` = "20";
UPDATE `Zusammenfassung` SET `IMAGE`="295" WHERE `IMAGE` = "21";
UPDATE `Zusammenfassung` SET `IMAGE`="296" WHERE `IMAGE` = "22";
UPDATE `Zusammenfassung` SET `IMAGE`="297" WHERE `IMAGE` = "23";
UPDATE `Zusammenfassung` SET `IMAGE`="298" WHERE `IMAGE` = "24";
UPDATE `Zusammenfassung` SET `IMAGE`="299" WHERE `IMAGE` = "25";
UPDATE `Zusammenfassung` SET `IMAGE`="300" WHERE `IMAGE` = "26";
UPDATE `Zusammenfassung` SET `IMAGE`="301" WHERE `IMAGE` = "27";
UPDATE `Zusammenfassung` SET `IMAGE`="302" WHERE `IMAGE` = "28";
UPDATE `Zusammenfassung` SET `IMAGE`="303" WHERE `IMAGE` = "29";
UPDATE `Zusammenfassung` SET `IMAGE`="304" WHERE `IMAGE` = "30";
UPDATE `Zusammenfassung` SET `IMAGE`="305" WHERE `IMAGE` = "31";
UPDATE `Zusammenfassung` SET `IMAGE`="306" WHERE `IMAGE` = "32";
UPDATE `Zusammenfassung` SET `IMAGE`="307" WHERE `IMAGE` = "33";
UPDATE `Zusammenfassung` SET `IMAGE`="308" WHERE `IMAGE` = "34";
UPDATE `Zusammenfassung` SET `IMAGE`="309" WHERE `IMAGE` = "35";
UPDATE `Zusammenfassung` SET `IMAGE`="310" WHERE `IMAGE` = "36";