<?php
$proof = new reference($item->manifestation['systemManifestation'], $item->manifestation['idManifestation']);
$proofWork = new reference($item->work['systemWork'], $item->work['idWork']);
?>
                <p><?php if ($persons): ?><span class="authorList"><?php echo $persons; ?>: </span><?php endif; ?><?php if ($item->titleBib and $item->titleCat): ?><span class="titleBib"><?php echo $item->titleBib; ?></span><span class="titleCat"><?php echo $item->titleCat; ?></span><?php elseif ($item->titleBib): ?><span class="titleBib"><?php echo $item->titleBib; ?></span><span class="titleCat">[Recherchierter Titel:] <?php echo $item->titleBib; ?></span><?php elseif ($item->titleCat): ?><span class="titleBib">[Titel im Altkatalog:] <?php echo $item->titleCat; ?></span><span class="titleCat"><?php echo $item->titleCat; ?></span><?php endif; ?><?php if ($item->bound === 0 or $item->bound == 'ungebunden'): ?>, ungebunden<?php endif; ?><?php if ($item->volumes > 1): ?><span class="volumes">, <?php echo $item->volumes; ?> Bde.</span><?php endif; ?><?php if ($published): ?><span class="published">, <?php echo $published; ?></span><?php endif; ?>
                    <a id="link<?php echo $item->anchor; ?>" href="javascript:toggle('<?php echo $item->anchor; ?>')">Mehr</a>
                </p>
                <div id="<?php echo $item->anchor;?>" style="display:none; padding-top:0px; padding-bottom:15px; padding-left:10px;">
<?php if ($sourceLink): ?>
                    <?php echo $sourceLink; ?><br /><?php endif; ?>
<?php if ($item->histShelfmark): ?>                    Altsignatur: <?php echo $item->histShelfmark; ?><br/>
<?php endif; ?>
<?php if ($originalLink): ?>                    <?php echo $originalLink; ?><br />
<?php endif; ?>
<?php if ($proofWork->valid): ?>                    <?php if ($item->work['titleWork']): ?>Enthaltenes Werk: <a href="<?php echo $proofWork->url; ?>" title="Anzeigen in <?php echo $proofWork->nameSystem; ?>" target="_blank"><?php echo $item->work['titleWork']; ?></a><?php else: ?>Datensatz Werk anzeigen: <?php echo $proofWork->link; ?><?php endif; ?><br />
<?php endif; ?>
<?php if ($proof->valid): ?>                    Nachweis: <?php echo $proof->link; ?><br />
<?php endif; ?>
<?php if ($copiesHAB): ?>                    <?php echo $copiesHAB; ?><br />
<?php endif; ?>
<?php if ($item->comment): ?>                    <?php echo makeComment($item->comment); ?><br />
<?php endif; ?>
<?php foreach ($item->persons as $person): ?>                    <?php if ($person->role == 'borrower'): ?>Entliehen von <?php echo $person->persName; ?><?php if ($person->dateLending != array()): ?> <?php echo implode(', ', $person->dateLending) ?><?php endif; ?><br /><?php endif; ?>
<?php endforeach; ?>
<?php if ($digiLink): ?>                    <?php echo $digiLink; ?>
<?php endif; ?>
                </div>
