            <div id="chartdiv" style="width:100%;min-height:<?php echo $height; ?>px"></div>
                        
            <script>
            am4core.ready(function() {

            // Themes begin
            am4core.useTheme(am4themes_moonrisekingdom);
            am4core.useTheme(am4themes_animated);
            // Themes end

            var chart = am4core.create("chartdiv", am4plugins_forceDirected.ForceDirectedTree);

            var networkSeries = chart.series.push(new am4plugins_forceDirected.ForceDirectedSeries())
            networkSeries.dataFields.linkWith = "linkWith";
            networkSeries.dataFields.name = "name";
            networkSeries.dataFields.id = "id";
            networkSeries.dataFields.value = "value";
            networkSeries.dataFields.children = "children";

            networkSeries.dataFields.color = "color";
            networkSeries.minRadius = 0.2
            networkSeries.maxRadius = 1

            networkSeries.nodes.template.label.text = "{name}"
            networkSeries.fontSize = 9;
            networkSeries.linkWithStrength = 1;

            var nodeTemplate = networkSeries.nodes.template;
            nodeTemplate.tooltipText = "{name}";
            nodeTemplate.fillOpacity = 1;
            nodeTemplate.label.hideOversized = true;
            nodeTemplate.label.truncate = true;

            var linkTemplate = networkSeries.links.template;
            linkTemplate.strokeWidth = 1;
            var linkHoverState = linkTemplate.states.create("hover");
            linkHoverState.properties.strokeOpacity = 1;
            linkHoverState.properties.strokeWidth = 2;

            nodeTemplate.events.on("over", function (event) {
                var dataItem = event.target.dataItem;
                dataItem.childLinks.each(function (link) {
                    link.isHover = true;
                })
            })

            nodeTemplate.events.on("out", function (event) {
                var dataItem = event.target.dataItem;
                dataItem.childLinks.each(function (link) {
                    link.isHover = false;
                })
            })

            networkSeries.data = <?php echo $series; ?>;


            });
            </script>